#!/bin/bash

# 스크립트가 위치한 디렉토리로 이동
cd "$(dirname "$0")" || exit

# 파일이 위치한 디렉토리 정의
FILES_DIR="./files"

# 각 알파벳 (a부터 z)에 대한 폴더 생성
for letter in {a..z}; do
    mkdir -p "$letter"
done

# 파일 이름의 첫 글자를 기준으로 해당 폴더로 파일 이동
for file in "$FILES_DIR"/*; do
    if [[ -f "$file" ]]; then
        filename=$(basename "$file")
        first_letter=${filename:0:1}
        lowercase_first_letter=$(echo "$first_letter" | tr '[:upper:]' '[:lower:]')
        
        mv "$file" "$lowercase_first_letter"
    fi
done

echo "success !"
